ALTER TABLE users DROP CONSTRAINT valid_role;

ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(20);

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'COMMON';

ALTER TABLE users
    ADD CONSTRAINT valid_role CHECK (role IN ('ADMIN', 'COMMON'));
